### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by philmccarthy** [zwsaile/mod_0_assessment#1]
@zwsaile, really nice work on the assessment. I can tell you have a solid understanding of JavaScript syntax, datatypes, and how to model data using objects. You are officially technical ready. Keep up the hard work moving forward and let me know if you have any questions. As mentioned on the Mod 0 site, we will be reviewing your Mod 1 Prework to determine promotion to Mod 1 - finish strong!

**Comment by zwsaile** [comment]
Thanks Phil, I appreciate you looking over this stuff for me. I don't know how much sway I have over who I am paired with, but it would be cool to keep this journey going with you as a mentor if you're open to it.
